// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZCPTTjTLSueaof54nSb-1-dZjaoRU9c',
    appId: '1:3881269783:web:da884233cef44914c63a52',
    messagingSenderId: '3881269783',
    projectId: 'atten-project',
    authDomain: 'atten-project.firebaseapp.com',
    databaseURL: 'https://atten-project-default-rtdb.firebaseio.com',
    storageBucket: 'atten-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBht9fY_xqhaxR474yvH57p8DUTtDU0Qa4',
    appId: '1:3881269783:android:44aa632eee750bb6c63a52',
    messagingSenderId: '3881269783',
    projectId: 'atten-project',
    databaseURL: 'https://atten-project-default-rtdb.firebaseio.com',
    storageBucket: 'atten-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKzX_pzqsy9JKwpZMk_ysaFciYh4yusU',
    appId: '1:3881269783:ios:31ad3cef915b95f6c63a52',
    messagingSenderId: '3881269783',
    projectId: 'atten-project',
    databaseURL: 'https://atten-project-default-rtdb.firebaseio.com',
    storageBucket: 'atten-project.appspot.com',
    iosClientId: '3881269783-triscf8c1h90q2a7ineden529787qsve.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbKzX_pzqsy9JKwpZMk_ysaFciYh4yusU',
    appId: '1:3881269783:ios:31ad3cef915b95f6c63a52',
    messagingSenderId: '3881269783',
    projectId: 'atten-project',
    databaseURL: 'https://atten-project-default-rtdb.firebaseio.com',
    storageBucket: 'atten-project.appspot.com',
    iosClientId: '3881269783-triscf8c1h90q2a7ineden529787qsve.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
